package:
  name: kmetashot
  version: "1.0"

source:
#   git_url: https://github.com/gdefazio/kMetaShot
  path: /home/giuseppedefazio/Documenti/kMetaShot_HQ_paper/kMetaShot_github/kMetaShot

build:
  script: python /home/giuseppedefazio/Documenti/kMetaShot_HQ_paper/kMetaShot_github/kMetaShot/conda_recipes/setup.py install
#  script: python -m pip install --no-deps --ignore-installed /home/giuseppedefazio/Documenti/kMetaShot_HQ_paper/kMetaShot_github/kMetaShot
  number: 0
  build: beta
  preserve_egg_dir: True

channels:
  - conda-forge

requirements:
  host:
    - python ==3.7
    - pip
    - setuptools

  run:
    - python ==3.7
    - numpy >=1.18.1
    - numba >=0.51.2
    - python-wget
    - pandas >=1.0.4
    - mmh3
    - bitarray >=1.2.1
    - h5py >=2.9.0
    - hdf5 >=1.10.4
    - argcomplete >=1.11.1
    - pytables >=3.6.1

test:
  command:
    - kMetaShot_classifier_NV.py --help



