package:
  name: kmetashot
  version: "1.0"

source:
#   git_url: https://github.com/gdefazio/kMetaShot
  path: /home/giuseppedefazio/Documenti/tesi_dottorale/kMetaShot/

build:
  number: 0
  build: beta
  preserve_egg_dir: True

requirements:
  host:
    - python ==3.7
    - pip
    - setuptools
#  build:
#    - python ==3.7
  run:
    - python ==3.7
    - numpy ==1.18.1
    - numba ==0.51.2
    - wget
    - pandas ==1.0.4
    - mmh3
    - bitarray ==1.2.1
    - h5py ==2.9.0
    - hdf5 ==1.10.4
    - argcomplete ==1.11.1

#requirements:
#  build:
#    - python >=3.7
#    - setuptools
#    - numpy >=1.18.1
#    - numba >=0.51.2
#    - wget
#    - pandas
#    - mmh3
#    - bitarray
#    - h5py
#    - hdf5
#    - argcomplete
#
#  run:
#    - python >=3.7
#    - numpy >=1.18.1
#    - numba >=0.51.2
#    - wget
#    - pandas
#    - mmh3
#    - bitarray
#    - h5py
#    - hdf5
#    - argcomplete

test:
  command:
    - kMetaShot_test.py



